version: "3.9"
services:
  gerimedica-service:
    container_name: gerimedica-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXTERNAL_PORT-8080}:${APP_PORT-8080}
    environment:
      server_port: ${APP_PORT-8080}
      db_username: ${DB_USERNAME-admin}
      db_passwrod: ${DB_PASSWORD-changeit}

