spring:
  application:
    name: example-service
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file_size:50MB}
      max-request-size: ${file_size:50MB}
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format:
          sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:exampledb
    username: ${db_username:changeIt}
    password: ${db_password:changeIt}
server:
  port: ${server_port:8080}
  tomcat:
    max-http-form-post-size: ${file_size:50MB}
    max-swallow-size: ${file_size:50MB}
